In [1]:
import torch
torch.cuda.is_available()

True

In [19]:
a = torch.randn(5,3)
a

tensor([[ 1.4175, -1.6927,  0.3563],
        [-0.2580, -1.4198,  2.0559],
        [-0.8909,  0.8677, -0.0892],
        [-0.1695, -0.8295,  2.3951],
        [ 0.3504,  0.0501,  1.3034]])

In [20]:
u,s,v = torch.svd(a)

In [21]:

s = torch.diag(s)

In [22]:
u.matmul(s).matmul(v.T)

tensor([[ 1.4175, -1.6927,  0.3563],
        [-0.2580, -1.4198,  2.0559],
        [-0.8909,  0.8677, -0.0892],
        [-0.1695, -0.8295,  2.3951],
        [ 0.3504,  0.0501,  1.3034]])

In [24]:
u = u[:,:2]
s = torch.diag(s[:2])
v = v.T[:2,:]
u.matmul(s).matmul(v)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x5 and 3x3)

In [30]:
v = v.T[:2,:]
print(u,s,v,sep="\n")

tensor([[ 0.3533, -0.7808],
        [ 0.6234,  0.1540],
        [-0.1665,  0.4703],
        [ 0.6166,  0.3408],
        [ 0.2802,  0.1713]])
tensor([3.9250, 2.2465])
tensor([[ 0.1228, -0.5414,  0.8317],
        [-0.6958,  0.5506,  0.4612]])


In [53]:
from model.nwp_lstm import LSTM
from utils import Config
config = Config(json_path="config/reddit_config.json")
model = LSTM(
            config.vocab_size,
            config.embedding_dim,
            config.hidden_dim,
            config.num_layers,
            config.dropout_rate,
            config.tie_weights,
        )

AttributeError: 'Config' object has no attribute 'vocab_size'

In [74]:
a = [1,2,3,4]
b = [1,2,3,4]
c = [1,2,3,4]
for i in zip(a,b,c):
    print(i)

(1, 1, 1)
(2, 2, 2)
(3, 3, 3)
(4, 4, 4)


In [55]:
a =  {1:2,3:2}

In [56]:
len(a)

2

In [105]:
import scipy
a = scipy.sparse.random(5,5, density=0.8, format='csr', dtype=None, random_state=1, data_rvs=np.ones)

In [106]:
print(a.indptr)
a.indices

[ 0  4  8 12 16 20]


array([0, 2, 3, 4, 0, 1, 3, 4, 0, 1, 3, 4, 0, 2, 3, 4, 0, 2, 3, 4],
      dtype=int32)

In [84]:
scipy.sparse.random(5,5, density=0.3, format='csr', dtype=None, random_state=1, data_rvs=np.ones).toarray()

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.]])

In [96]:
b = torch.randn(5,5)
# b.to_sparse_csr()
b

tensor([[ 0.3356, -0.7133, -0.2982, -0.0240,  0.5355],
        [-0.1418, -0.1583,  0.7155, -2.3161,  1.3413],
        [-0.7959,  0.9941,  0.2159, -0.2088,  0.2625],
        [ 0.5578,  1.0400, -1.6111, -0.3579,  0.3106],
        [ 0.7403,  0.4798, -0.5735,  0.6258,  0.5721]])

In [158]:
b = torch.tensor([[ 0.3356, -0.7133, 0, -0.0240,  0.5355],
        [-0.1418, -0.1583,  0.7155, -2.3161,  1.3413],
        [0,  0,  0, 0,  0],
        [ 0.5578,  1.0400, -1.6111, -0.3579,  0.3106],
        [ 0.7403,  0.4798, -0.5735,  0.6258,  0.5721]])

In [159]:
array = b.to_sparse_csr()

In [161]:
array

tensor(crow_indices=tensor([ 0,  4,  9,  9, 14, 19]),
       col_indices=tensor([0, 1, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
                           4]),
       values=tensor([ 0.3356, -0.7133, -0.0240,  0.5355, -0.1418, -0.1583,
                       0.7155, -2.3161,  1.3413,  0.5578,  1.0400, -1.6111,
                      -0.3579,  0.3106,  0.7403,  0.4798, -0.5735,  0.6258,
                       0.5721]), size=(5, 5), nnz=19, layout=torch.sparse_csr)

In [162]:
b = np.array([[ 0.3356, -0.7133, 0, -0.0240,  0.5355],
        [-0.1418, -0.1583,  0.7155, -2.3161,  1.3413],
        [-0.7959,  0.9941,  0.2159, 0,  0.2625],
        [ 0.5578,  1.0400, -1.6111, -0.3579,  0.3106],
        [ 0.7403,  0.4798, -0.5735,  0.6258,  0.5721]])

In [169]:
z_list = np.where(b==0)

In [165]:
a = scipy.sparse.random(5,5, density=0.3, format='csr', dtype=None, random_state=1, data_rvs=np.ones)
a.toarray()

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.]])

In [166]:
array = a.toarray()*b


In [125]:
values = torch.tensor(array).to_sparse_csr().values()

In [168]:
print(a.indptr)
print(a.indices)
print(values)

[0 1 2 3 6 8]
[2 4 3 0 2 3 2 3]
tensor([ 1.3413,  0.5578, -1.6111, -0.3579, -0.5735,  0.6258],
       dtype=torch.float64)


In [ ]:
for t in z_list:
    count = 0
    for i in a.indptr[t[0]:]:
        if t[1] == i:
            values.insert(a.indptr[t[0]],0)
        else:
            count = count + 1
    

In [127]:

torch.sparse_csr_tensor(crow_indices=a.indptr, col_indices=a.indices, values=values).to_dense()
        
    

RuntimeError: The size of tensor a (8) must match the size of tensor b (6) at non-singleton dimension 0

In [152]:
array

array([[ 0.    , -0.    ,  0.    , -0.    ,  0.    ],
       [-0.    , -0.    ,  0.    , -0.    ,  1.3413],
       [-0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.5578,  0.    , -1.6111, -0.3579,  0.    ],
       [ 0.    ,  0.    , -0.5735,  0.6258,  0.    ]])

In [154]:
a.toarray()

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.]])